LLAMA_RECIPES_TARBALL_FILENAME = "llama_recipes.tar.gz"


# SM HUGGING FACE CONSTANTS
TRUE_STR = "True"
FALSE_STR = "False"
NONE_STR = "None"
PT_STR = "pt"
EPOCH = "epoch"
STEPS = "steps"
NO = "no"

DEFAULT_PEFT_TYPE = "None"
DEFAULT_LORA_QUANTIZATION_BITS = 16
DEFAULT_DOUBLE_QUANT = True
DEFAULT_QUANT_TYPE = "nf4"
DEFAULT_DEEPSPEED = True
DEFAULT_INSTRUCTION_TUNING = TRUE_STR





# LLAMA FINETUNING CONSTANTS
DEFAULT_LORA_R = 8
DEFAULT_LORA_ALPHA = 32
DEFAULT_LORA_DROPOUT = 0.05
DEFAULT_INT8_QUANTIZATION = False
DEFAULT_ENABLE_FSDP = True
DEFAULT_CHAT_DATASET = False
DEFAULT_TARGET_MODULES = "q_proj,v_proj"